const Haryana = [
    {
      state: "haryana",
      totalArea: 44212,
      landCover : 41209,
      forestCover: 3003,
      percentageOfForestCover: 6.79,
      cities: [
        {
        city: "Faridabad", 
        totalArea: 741, 
        landCover: 661, 
        forestCover: 80, 
        percentageOfForestCover: 10.79,
        },
        {
        city: "Gurgaon", 
        totalArea: 1258, 
        landCover: 1142, 
        forestCover: 116, 
        percentageOfForestCover: 9.22,
        },
        {
        city: "Panipat", 
        totalArea: 1268, 
        landCover: 1252, 
        forestCover: 16, 
        percentageOfForestCover: 1.26,
        },
        {
        city: "Ambala", 
        totalArea: 1569, 
        landCover: 1518, 
        forestCover: 51, 
        percentageOfForestCover: 3.25,
        },
        {
        city: "Yamunanagar", 
        totalArea: 1768, 
        landCover: 1575, 
        forestCover: 193, 
        percentageOfForestCover: 10.91,
        },
        {
        city: "Rohtak", 
        totalArea: 1745, 
       landCover: 1724, 
        forestCover: 21, 
        percentageOfForestCover: 1.20,
        },
        {
        city: "Hisar", 
        totalArea: 3983, 
        landCover: 3925, 
        forestCover: 58, 
        percentageOfForestCover: 5.82,
        },
        {
        city: "Karnal", 
        totalArea: 2520, 
        landCover: 2488, 
        forestCover: 32, 
        percentageOfForestCover: 1.26,
        },
        {
        city: "Sonipat", 
        totalArea: 2122, 
        landCover: 2101, 
        forestCover: 21, 
        percentageOfForestCover: 0.98,
        },
        {
        city: "Panchkula", 
        totalArea: 898, 
        landCover: 507, 
        forestCover: 391, 
        percentageOfForestCover: 43.54,
        },
        {
        city: "Bhiwani", 
        totalArea: 4778, 
        landCover: 4664, 
        forestCover: 114, 
        percentageOfForestCover: 2.38,
        },
        {
        city: "Sirsa", 
        totalArea: 4277, 
        landCover: 4220, 
        forestCover: 57, 
        percentageOfForestCover: 1.33,
        },
        {
        city: "Jind", 
        totalArea: 2702, 
        landCover: 2681, 
        forestCover: 21, 
        percentageOfForestCover: 0.77,
        },
        {
        city: "Kaithal", 
        totalArea: 2317, 
        landCover: 2260, 
        forestCover: 57, 
        percentageOfForestCover: 2.46,
        },
        {
        city: "Rewari", 
        totalArea: 1594, 
        landCover: 1532, 
        forestCover: 62, 
        percentageOfForestCover: 3.88,
        },
        {
        city:"Fatehabad",
        totalArea:2538,
        landCover : 2520,
        forestCover : 18,
        percentageOfForestCover:0.70,

        },
        {
        city:"Jhajjar",
        totalArea:1834,
        landCover:1812,
        forestCover:26,
        percentageOfForestCover:1.41,
        },  
        {
        city:"Kurukshetra",
        totalArea:1530,
        landCover:1490,
        forestCover:40,
        percentageOfForestCover:2.61,
        },
        {
        city:"Mahendragarh",
        totalArea:1899,
        landCover:1796,
        forestCover:103,
        percentageOfForestCover:5.42,
        },
        {
        city:"Mewat",
        totalArea:1507,
        landCover:1396,
        forestCover:111,
        percentageOfForestCover:7.36,
        },
        {
        city:"Palwal",
        totalArea:1359,
        landCover:1345,
        forestCover:14,
        percentageOfForestCover:1.03,
        }
      ]
    }
]
module.exports = Haryana;